version: '3.8'
services:
  stats-server:
    build: ./stats-server/http-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats_server
      - SPRING_DATASOURCE_USERNAME=stats
      - SPRING_DATASOURCE_PASSWORD=stats

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats_server
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  ewm-service:
    build: ./ewm-service

    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_service
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm


  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6545:5432"
    environment:
      - POSTGRES_DB=ewm_service
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
